---
# Source: tts-translator/templates/tts-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-translator-data-pvc
  namespace: n8n-vps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Source: tts-translator/templates/tts-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tts-translator
  namespace: n8n-vps
spec:
  selector:
    app: tts-translator
  ports:
    - port: 8080
      targetPort: 8080
---
# Source: tts-translator/templates/tts-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-translator
  namespace: n8n-vps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-translator
  template:
    metadata:
      labels:
        app: tts-translator
    spec:
      containers:
        - name: tts-translator
          image: tmcx/tts-translator:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENABLE_CORS
              value: "true"
            - name: LT_LOAD_ONLY
              value: "pt,es"
            - name: LT_PORT
              value: "8089"
            - name: API_PORT
              value: "8080"
            - name: LT_HOST
              value: "0.0.0.0"
          volumeMounts:
            - name: data
              mountPath: /usr/share/tts-translator
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tts-translator-data-pvc
---
# Source: tts-translator/templates/tss-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tts-translator-ingress
  namespace: n8n-vps
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: nginx
  rules:
    - host: tts-translator-test.devops-master.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tts-translator
                port:
                  number: 8080
  tls:
    - hosts:
        - tts-translator-test.devops-master.shop
      secretName: tts-translator-tls
