apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.pvcName }}
  namespace: {{ .Values.redis.namespace }}
spec:
  accessModes:
    - {{ .Values.redis.accessModes }}
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
