apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.pvcName }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  accessModes:
    - {{ .Values.postgresql.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
