apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.evolutionApi.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          env:
            {{- range $key, $val := .Values.postgresql.env }}
            - name: {{ $key }}
              {{- if hasKey $val "value" }}
              value: "{{ $val.value }}"
              {{- else if hasKey $val "valueFrom" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.valueFrom.secretKeyRef.name }}
                  key: {{ $val.valueFrom.secretKeyRef.key }}
              {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.pvcName }}
