apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.evolution-api.secretName }}"
  namespace: {{ .Values.evolution-api.namespace }}
  labels:
    app: {{ .Values.evolution-api.name }}
stringData:
  N8N_BASIC_AUTH_USER: {{ .Values.evolution-api.username }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.evolution-api.password }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.evolution-api.postgres.password }}