n8n:
  name: n8n
  namespace: n8n-vps
  secretName: n8n-secrets
  image: n8nio/n8n:1.89.2
  protocol: https
  port: 5678
  domain_name: n8n-test.devops-master.shop
  webhookUrl: "https://n8n-test.devops-master.shop"
  timezone: America/Sao_Paulo
  basic:
    auth_active: true
  secure_cookie: true
  enforce_settings_file: true
  postgres:
    db_type: postgresdb
    host: postgres
    port: "5432"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: n8n-tls
  queue:
    mode: redis
  redis:
    host: redis
    port: 6379
    password: ""
    replicas: 1
    image: redis:7
    persistence:
      enabled: true
      pvcName: redis-pvc
      accessModes: ReadWriteOnce
      size: 1Gi