n8n:
  name: n8n
  namespace: n8n-vps
  secretName: n8n-secrets
#  image: n8nio/n8n:1.91.2 # (original)  
  image: sevenleo/n8n-python:latest # (custom)
  imagePullPolicy: Always
  protocol: https
  port: 5678
  domain_name: n8n-4.devops-master.shop
  webhookUrl: "https://n8n-4.devops-master.shop"
  timezone: America/Sao_Paulo
  pvcName: n8n-data
  accessModes: ReadWriteOnce
  storage: 3Gi
  volumeMounts:
    name: n8n-data
    mountPath: /home/node/.n8n
  basic:
    auth_active: false
  secure_cookie: true
  postgres:
    db_type: postgresdb
    host: postgres
    port: "5432"
    resources:
      requests:
        cpu: "128m"
        memory: "512Mi"
      limits:
        cpu: "256m"
        memory: "1Gi"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: n8n-tls
  queue:
    mode: redis
  redis:
    host: redis
    port: 6379
    password: ""
    replicas: 1
    image: redis:7
    persistence:
      enabled: true
      pvcName: redis-pvc
      accessModes: ReadWriteOnce
      size: 1Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
  replicas: 1
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "1Gi"
