n8n:
  name: n8n
  namespace: n8n-vps
  secretName: n8n-secret
  image: n8nio/n8n:1.88.0
  protocol: https
  port: 5678
  domain_name: n8n-test.devops-master.shop
  webhookUrl: "https://n8n-test.devops-master.shop"
  timezone: America/Sao_Paulo
  postgres:
    db_type: postgresdb
    host: postgres
    port: "5432"
    database: n8n
    user: n8n
    password: supersecreto
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: n8n-tls