apiVersion: v1
kind: Service
metadata:
  name: udemy-python-app
  namespace: udemy-python-app
spec:
  selector:
    app: udemy-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000