- name: Instala o cert-manager no cluster (CRDs + namespace)
  tags: [cert_bundle]
  shell: kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
  register: install_cert_manager

- name: Aguarda pods do cert-manager (controller, cainjector, webhook)
  tags: [cert_bundle]
  shell: |
    kubectl rollout status deployment/cert-manager -n cert-manager --timeout=90s
    kubectl rollout status deployment/cert-manager-cainjector -n cert-manager --timeout=90s
    kubectl rollout status deployment/cert-manager-webhook -n cert-manager --timeout=90s
  register: certmanager_status
  until: certmanager_status.rc == 0
  retries: 3
  delay: 10

- name: Aguarda CRD ClusterIssuer estar disponível
  tags: [cert_bundle]
  shell: kubectl get crd clusterissuers.cert-manager.io
  register: cert_crd_check
  until: cert_crd_check.rc == 0
  retries: 10
  delay: 6

- name: Cria ou atualiza o ClusterIssuer (letsencrypt-staging)
  tags: [cert_bundle]
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ issuer_name }}"
      spec:
        acme:
          server: "{{ issuer_server }}"
          email: "{{ issuer_email }}"
          privateKeySecretRef:
            name: "{{ issuer_secretname }}"
          solvers:
            - http01:
                ingress:
                  # 'ingressClassName' é o campo correto para versões recentes
                  ingressClassName: "{{ issuer_ingressclass }}"
