ttsTranslator:
  name: tts-translator
  namespace: n8n-vps

  # Imagem base usada nos dois containers (pode separar se quiser)
  image: tmcx/tts-translator:latest

  domain_name: tts-translator-test.devops-master.shop

  env:
    ENABLE_CORS: "true"                      # usado pelo container node
    LT_LOAD_ONLY: "pt,es"                    # usado por ambos
    API_PORT: "8080"                         # usado pelo container node
    LT_PORT: "8089"                          # usado pelo libretranslate
    LT_HOST: "0.0.0.0"                       # usado pelo libretranslate

  service:
    port: 8080
    targetPort: 8080

  persistence:
    enabled: true
    mountPath: /usr/share/tts-translator
    pvcName: tts-translator-data-pvc
    accessModes: ReadWriteOnce
    storage: 1Gi
    volume: data

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: tts-translator-tls
