ttsTranslator:
  name: tts-translator
  namespace: n8n-vps
  image: tmcx/tts-translator:latest
  domain_name: tts-translator-test.devops-master.shop
  env:
    ENABLE_CORS: true
    LT_LOAD_ONLY: pt,en
    API_PORT: "8080"
    LT_PORT: "8089"
  service:
    port: 8080
    targetPort: 8080
  persistence:
    enabled: true
    mountPath: /usr/share/tts-translator
    pvcName: tts-translator-data-pvc
    accessModes: ReadWriteOnce
    storage: 1Gi
    volume: data
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: tts-translator-tls
