apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-translator
  namespace: n8n-vps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-translator
  template:
    metadata:
      labels:
        app: tts-translator
    spec:
      containers:
        - name: tts-translator
          image: tmcx/tts-translator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENABLE_CORS
              value: "true"
            - name: LT_LOAD_ONLY
              value: "pt,en"
            - name: API_PORT          # ← porta que o Node usa
              value: "8080"
          volumeMounts:
            - name: tts-data
              mountPath: /usr/share/tts-translator
      volumes:
        - name: tts-data
          persistentVolumeClaim:
            claimName: tts-translator-data
