apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.postgres.servicePort }}
        envFrom:
        - secretRef:
            name: "{{ .Values.postgres.secretName }}"
        volumeMounts:
        - mountPath: {{ .Values.postgres.mountPath }}
          name: {{ .Values.postgres.volume }}
      volumes:
      - name: {{ .Values.postgres.volume }}
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvcName }}
