apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.postgres.secretName }}"
  namespace: {{ .Values.postgres.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
stringData:
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.database }}