apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evolution-postgres-secrets
  namespace: n8n-vps
spec:
  encryptedData:
    POSTGRES_USER: "n8n"
    POSTGRES_PASSWORD: "supersecreto"
    POSTGRES_DB: "n8n"
  template:
    metadata:
      name: evolution-postgres-secrets
      namespace: n8n-vps
    type: Opaque