postgres:
  name: postgres
  namespace: n8n-vps
  image: postgres:15
  secretName: n8n-postgres-secrets  # 👉 nome usado no SealedSecret
  storage: 1Gi
  servicePort: 5432
  volume: pgdata
  replicas: 1
  pvcName: postgres-pvc
  mountPath: /var/lib/postgresql/data
  accessModes: ReadWriteOnce
