apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gt-dash
  namespace: gt-dash
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          {{- range .Values.ingress.hosts[0].paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: gt-dash
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
  tls:
    - secretName: {{ .Values.ingress.tls[0].secretName }}
      hosts:
        {{- range .Values.ingress.tls[0].hosts }}
        - {{ . }}
        {{- end }}