apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gt_dash.gt_redis.name }}
  namespace: {{ .Values.gt_dash.namespace }}
spec:
  ports:
    - port: {{ .Values.gt_dash.gt_redis.port }}
      targetPort: {{ .Values.gt_dash.gt_redis.port }}
  selector:
    app: {{ .Values.gt_dash.gt_redis.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gt_dash.gt_redis.name }}
  namespace: {{ .Values.gt_dash.namespace }}
  labels:
    app: {{ .Values.gt_dash.gt_redis.name }}
spec:
  replicas: {{ .Values.gt_dash.gt_redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.gt_dash.gt_redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gt_dash.gt_redis.name }}
    spec:
      containers:
        - name: {{ .Values.gt_dash.gt_redis.name }}
          image: {{ .Values.gt_dash.gt_redis.iname }}
          ports:
            - containerPort: {{ .Values.gt_dash.gt_redis.port }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
