---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gt-dash-secrets
  namespace: gt-dash
spec:
  encryptedData:
    GITHUB_TOKEN: AgAFjW9tzYGlXIZWDMKS+rNFbPp+xxY5XE0kjhGzmVaeOF1fwy5FdrrSGO3Z5HOP26zwjl8ybj6BCaLeXR4VxcMIw3o78iwbY2/PGL6dFXAv8+wImCuUevPP9mcd8FPTgRaBdO2Do5iPD2Y6xQiFBNaBY5H2XZcrAS18uKP8+f+dv8V28tP1pHklz7kG+znxRdLcU+gDAgGAauXoLrb9BuRKuAA+pKEK4QGiZB7VT64HBvfx8S7RL1u0zM00i99ynJlO0ZRQAqb88batAXlKNcXuatL1HSKHH0e5UKlkZrWu/sjbkOkJWsvuhNmfWofxls7QvQ3yOx4iws7ipthhKR6DrjKJIszA7SmCznm6+8moNTi6VaYN9nxFzRtxmG95kUI0F1/LAuXmFwAHSWGxt+HEhE8TVyvRoKfFFE71Kfif3iDNfBWo7Mn6zA54Gk/pNbA+ZadPDjR+b6Hd6SJRtBS1VEXdh+wuj67ClB7TDtp2LM787vUrYNTm3hePIVDtg8pgkE7V+RGjpmMatk+syc1Ps2BG75IF93/0DmUCNt0iFHCmCb9dGaqfXqXe+ux71FmcZZ/AH6oFHvxRjxu5P0tefu3I1T2KrLPL9lWzWrBhLaq+JQeGFksE5fwe+7impYkuw+SXMgkd4tTTzFfDmQ3VCo2LHEu5VpZBDTvHYQAWFZxatjiGoj13KwPEVJPk3Q81EkfE/rIrKi1ZED4zVzKYIu72WoMQ3vYrtbi7uDFRUekLXUUlbXcb/kCSiPbn6FfI0RSBdVG+7j0uQaaQVwfZyUDLCCPI2ge4Wo8j6WT1h12gCKxxKzNscvOr+7A=
  template:
    metadata:
      creationTimestamp: null
      name: gt-dash-secrets
      namespace: gt-dash
