apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gt_dash.name }}
  namespace: {{ .Values.gt_dash.namespace }}
spec:
  selector:
    app: {{ .Values.gt_dash.namespace }}
  ports:
    - protocol: TCP
      port: {{ .Values.gt_dash.service.port }}
      targetPort: {{ .Values.gt_dash.service.port }}