---
- name: Deploy de aplicações no cluster KIND
  hosts: vps_hostinger
  become: yes
  gather_facts: false

  vars:
    helm_charts_dir: "{{ playbook_dir }}/../helm-charts"

  pre_tasks:
    - name: Confirma acesso ao cluster
      command: kubectl get nodes
      register: cluster_check
      failed_when: cluster_check.rc != 0

  roles:
    - role: cert_bundle
    - role: argocd
    - role: argocd_image_updater
    - role: sealed_secrets

  post_tasks:
    - name: Exibe status final da configuração
      debug:
        msg: "✅ Cert-manager, ArgoCD e Sealed Secrets gerados no cluster KIND."