- name: Cria Applications do ArgoCD - n8n
  hosts: all
  become: true
  tasks:
    - name: Verifica se os Applications já existem no cluster
      shell: |
        kubectl get application {{ item }} -n argocd --ignore-not-found
      register: resultado
      changed_when: false
      loop:
        - n8n-postgres
        - evolution-api
        - n8n

    - name: Aplica Application do ArgoCD se ainda não existir
      shell: kubectl apply -f /root/argo-apps/{{ item }}.yaml -n argocd
      when: resultado.results[item_index].stdout == ""
      loop:
        - n8n-postgres
        - evolution-api
        - n8n
      loop_control:
        index_var: item_index

