{{- if .Values.gtDash.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.gtDash.name }}
  namespace: {{ .Values.gtDash.namespace }}
  annotations:
    {{- range $key, $value := .Values.gtDash.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.gtDash.ingress.className }}
  rules:
    {{- range .Values.gtDash.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.gtDash.name }}
                port:
                  number: {{ $.Values.gtDash.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.gtDash.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.gtDash.ingress.tls.secretName }}
      hosts:
        {{- range .Values.gtDash.ingress.tls.hosts }}
        - {{ . }}
        {{- end }}
  {{- end }}
{{- end }}