---
galaxy_info:
  author: Leonardo Sete
  description: Role para instalar o Sealed Secrets no cluster Kubernetes
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
