apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ttsTranslator.name }}
  namespace: {{ .Values.ttsTranslator.namespace }}
  labels:
    app: {{ .Values.ttsTranslator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ttsTranslator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ttsTranslator.name }}
    spec:
      containers:
        - name: {{ .Values.ttsTranslator.name }}
          image: {{ .Values.ttsTranslator.image }}
          ports:
            - containerPort: {{ .Values.ttsTranslator.service.port }}
#          args: {{- toYaml .Values.ttsTranslator.command | nindent 10 }}
          env:
            - name: ENABLE_CORS
              value: "{{ .Values.ttsTranslator.env.ENABLE_CORS }}"
            - name: LT_LOAD_ONLY
              value: "{{ .Values.ttsTranslator.env.LT_LOAD_ONLY }}"
            - name: LT_PORT
              value: "{{ .Values.ttsTranslator.env.LT_PORT }}"
          volumeMounts:
            - name: data
              mountPath: {{ .Values.ttsTranslator.persistence.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.ttsTranslator.persistence.pvcName }}
