apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.tts-translator.persistence.pvcName }}
  namespace: {{ .Values.tts-translator.namespace }}
spec:
  accessModes:
    - {{ .Values.tts-translator.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.tts-translator.persistence.storage }}
