apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-translator-data          # nome do claim
  namespace: n8n-vps                 # mesmo namespace do Deployment
spec:
  accessModes:
    - ReadWriteOnce                  # leitura/gravação por um único pod
  resources:
    requests:
      storage: 500Mi                 # espaço reservado
