apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.opentts.name }}
  namespace: {{ .Values.opentts.namespace }}
spec:
  selector:
    app: {{ .Values.opentts.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.tts-translator.service.port }}
      targetPort: {{ .Values.opentts.service.port }}
  type: ClusterIP
