apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ttsTranslator.name }}
  namespace: {{ .Values.ttsTranslator.namespace }}
spec:
  selector:
    app: {{ .Values.ttsTranslator.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ttsTranslator.service.port }}
      targetPort: {{ .Values.ttsTranslator.service.targetPort }}
