apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-translator
  namespace: n8n-vps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-translator
  template:
    metadata:
      labels:
        app: tts-translator
    spec:
      containers:
        - name: tts-translator
          image: tmcx/tts-translator:latest
          ports:
            - containerPort: 8080              # igual ao compose
          env:
            - name: ENABLE_CORS
              value: "true"
            - name: LT_LOAD_ONLY
              value: "pt,en"
          volumeMounts:
            - name: tts-data
              mountPath: /usr/share/tts-translator                   # equivalente ao volume anônimo
      volumes:
        - name: tts-data
          persistentVolumeClaim:
            claimName: tts-translator-data
