apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tts.name }}
  namespace: {{ .Values.tts.namespace }}
spec:
  selector:
    app: {{ .Values.tts.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.tts.port }}
      targetPort: {{ .Values.tts.target_port }}
