apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.n8n.secretName }}"
  namespace: {{ .Values.n8n.namespace }}
  labels:
    app: {{ .Values.n8n.name }}
stringData:
  N8N_BASIC_AUTH_USER: {{ .Values.n8n.username }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.password }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.n8n.postgres.password }}