apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  labels:
    app: n8n
stringData:
  N8N_BASIC_AUTH_USER: {{ .Values.n8n.username }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.password }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.n8n.postgres.password }}