apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.n8n.name }}
  namespace: {{ .Values.n8n.namespace }}
spec:
  selector:
    app: {{ .Values.n8n.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.n8n.port }}
      targetPort: {{ .Values.n8n.port }}