sealed_secrets_namespace: kube-system
sealed_secrets_release_name: sealed-secrets
sealed_secrets_chart: sealed-secrets/sealed-secrets
sealed_secrets_repo: https://bitnami-labs.github.io/sealed-secrets
