- name: Adiciona o repositório do Helm do Sealed Secrets
  tags: [sealed_secrets]
  shell: helm repo add sealed-secrets {{ sealed_secrets_repo }}
  register: sealed_repo_add
  changed_when: "'has been added' in sealed_repo_add.stdout or 'already exists' in sealed_repo_add.stdout"

- name: Atualiza os repositórios do Helm
  tags: [sealed_secrets]
  shell: helm repo update
  register: sealed_repo_update

- name: Instala o Sealed Secrets via Helm
  tags: [sealed_secrets]
  shell: |
    helm upgrade --install {{ sealed_secrets_release_name }} {{ sealed_secrets_chart }} \
      --namespace {{ sealed_secrets_namespace }} \
      --create-namespace
  register: install_sealed_secrets

- name: Aguarda o controller do Sealed Secrets estar pronto
  tags: [sealed_secrets]
  shell: kubectl rollout status deployment/sealed-secrets -n {{ sealed_secrets_namespace }} --timeout=60s
  register: sealed_rollout
  until: sealed_rollout.rc == 0
  retries: 3
  delay: 10
