################################################################################
# 01 – Configs VPS + Instalar Cluster KIND                                     #
#                                                                              #
# ▸ Disparo manual via workflow_dispatch                                       #
# ▸ Chama o workflow 02-infra-base via workflow_call                           #
################################################################################
name: 01-Configs VPS + Instalar Cluster KIND

on:
  workflow_dispatch:
    inputs:
      acionar_infra_base:
        description: "⚠️  Executar também o deploy da INFRA BASE? (cert-manager, ArgoCD…) "
        required: true
        default: false
        type: boolean

jobs:
  configure-vps-kind-cluster:
    runs-on: self-hosted

    steps:
    - name: 📦 Checkout repositório
      uses: actions/checkout@v4

    # 1 ▸ Instala pacotes necessários no runner
    - name: 🔧 Instala dependências (Ansible, SSH, kubectl)
      run: |
        echo "::group::Instalando dependências"
        sudo apt-get update -y
        sudo apt-get install -y ansible sshpass openssh-client curl
        ansible-galaxy collection install community.kubernetes
        curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        echo "::endgroup::"

    # 2 ▸ Prepara SSH
    - name: 🔐 Configura chave SSH
      run: |
        echo "::group::Configurando SSH"
        install -d -m 0700 ~/.ssh
        printf '%s' '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/${{ secrets.SSH_KEY_FILENAME }}
        chmod 600 ~/.ssh/${{ secrets.SSH_KEY_FILENAME }}
        ssh-keyscan -H ${{ secrets.VPS_HOSTNAME }} >> ~/.ssh/known_hosts
        echo "::endgroup::"

    - name: 🔍 Valida chave no runner
      run: ssh-keygen -y -f ~/.ssh/${{ secrets.SSH_KEY_FILENAME }} >/dev/null

    # 3 ▸ Executa playbook KIND
    - name: ⚙️ Playbook Ansible – KIND
      working-directory: ./ansible-hostinger
      run: |
        echo "::group::Executando playbook KIND"
        ansible-playbook -i inventory.ini 01-ansible-vps-kind.yaml
        echo "::endgroup::"

  # 4 ▸ Aciona workflow 02 (infra base) se habilitado
  deploy-infra-base:
    if: ${{ github.event.inputs.acionar_infra_base == 'true' }}
    needs: configure-vps-kind-cluster
    uses: ./.github/workflows/02-infra-base.yaml
    with:
      criar_infra_base: true
    secrets: inherit
