name: 04-Deploy-n8n-stack-via-ArgoCD

################################################################################
# Disparo manual (ou encadeado a partir do workflow-02)                        #
################################################################################
on:
  workflow_dispatch:

################################################################################
# Job único — aplica os manifests na VPS                                       #
################################################################################
jobs:
  aplicar-apps:
    runs-on: ubuntu-latest

    # Se quiser executar automaticamente depois do SealedSecrets,
    # basta chamar ESTE workflow no passo final do “02-infra-base”
    # ou adicionar um `workflow_call` e disparar em sequência.
    steps:
    - name: 📦 Checkout do repositório
      uses: actions/checkout@v4

    # ──────────────────────────────────────────────────────────────────────────
    # 1 ▸ Prepara SSH
    # ──────────────────────────────────────────────────────────────────────────
    - name: 🔐 Prepara chave SSH da VPS
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ vars.SSH_KEY_FILENAME }}
        chmod 600 ~/.ssh/${{ vars.SSH_KEY_FILENAME }}
        ssh-keyscan -H ${{ vars.VPS_HOSTNAME }} >> ~/.ssh/known_hosts

    # ──────────────────────────────────────────────────────────────────────────
    # 2 ▸ Copia manifests para a VPS
    # ──────────────────────────────────────────────────────────────────────────
    - name: 📁 Copia /root/argo-apps
      run: |
        ssh -i ~/.ssh/${{ vars.SSH_KEY_FILENAME }} ${{ vars.VPS_USER }}@${{ vars.VPS_HOSTNAME }} "mkdir -p /root/argo-apps"
        scp -i ~/.ssh/${{ vars.SSH_KEY_FILENAME }} argo-apps/*.yaml \
            ${{ vars.VPS_USER }}@${{ vars.VPS_HOSTNAME }}:/root/argo-apps/

    # ──────────────────────────────────────────────────────────────────────────
    # 3 ▸ Executa playbook Ansible (ou kubectl, se preferir)
    # ──────────────────────────────────────────────────────────────────────────
    - name: 🚀 Aplica Applications no ArgoCD
      working-directory: ./ansible-hostinger
      run: ansible-playbook -i inventory.ini ansible-deploy-n8n.yml

    # ──────────────────────────────────────────────────────────────────────────
    # 4 ▸ Resultado
    # ──────────────────────────────────────────────────────────────────────────
    - name: ✅ Resultado final
      run: |
        echo "====================== ✅ DEPLOY FINALIZADO ======================"
        echo "🌐 Acesse o ArgoCD: https://argocd-test.devops-master.shop"
