apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolution-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonardosete/kind-cluster-n8n.git
    targetRevision: HEAD
    path: apps/evolution-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-vps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Namespace
      name: n8n-vps
      jsonPointers:
        - /metadata/labels
