apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gt-dash-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonardosete/kind-cluster-n8n.git
    targetRevision: HEAD
    path: apps/gt-dash-helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gt-dash-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Namespace
      name: gt-dash-helm
      jsonPointers:
        - /metadata/labels